#!/bin/sh
scp -i "/Users/hee/Documents/keys/myworkspace.pem" -r /Users/hee/Documents/git2021-working/8-msa/workspace/service3/build/libs/service3*.jar ubuntu@ec2-13-125-231-210.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/app/service3
scp -i "/Users/hee/Documents/keys/myworkspace.pem" -r /Users/hee/Documents/git2021-working/8-msa/workspace/service3/run.sh ubuntu@ec2-13-125-231-210.ap-northeast-2.compute.amazonaws.com:/home/ubuntu/app/service3
ssh -i "/Users/hee/Documents/keys/myworkspace.pem" ubuntu@ec2-13-125-231-210.ap-northeast-2.compute.amazonaws.com "sudo chmod 777 /home/ubuntu/app/service3/run.sh"
ssh -i "/Users/hee/Documents/keys/myworkspace.pem" ubuntu@ec2-13-125-231-210.ap-northeast-2.compute.amazonaws.com "cd /home/ubuntu/app/service3; sh run.sh service3"
